apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-postgresql
  namespace: orders
  labels:
    app: orders-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-postgresql
  template:
    metadata:
      labels:
        app: orders-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: orders
            - name: POSTGRES_USER
              value: orders
            - name: POSTGRES_PASSWORD
              value: orders_pass
