apiVersion: v1
kind: Secret
metadata:
  name: orders
  namespace: orders
  labels:
    app: orders
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: orders
  SPRING_DATASOURCE_PASSWORD: orders_pass
