apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: checkout
  labels:
    app: checkout
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      serviceAccountName: checkout
      containers:
        - name: checkout
          image: public.ecr.aws/aws-containers/retail-store-sample-checkout:0.8.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: checkout
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
