apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: lab-app
data:
  AURORA_WRITER_ENDPOINT: "REPLACE_WITH_AURORA_WRITER_ENDPOINT"
  AURORA_READER_ENDPOINT: "REPLACE_WITH_AURORA_READER_ENDPOINT"
  AURORA_PORT: "3306"
  AURORA_DB_NAME: "appdb"
  VALKEY_ENDPOINT: "REPLACE_WITH_VALKEY_ENDPOINT"
  VALKEY_PORT: "6379"
